configure AWS in buid-ami workflow

diff --git a/.github/workflows/build-ami.yml b/.github/workflows/build-ami.yml
--- a/.github/workflows/build-ami.yml
+++ b/.github/workflows/build-ami.yml
@@ -2,7 +2,7 @@ name: Build AMI
 
 on:
   pull_request:
-    branches: 
+    branches:
       - main
     types: [closed]
 
@@ -32,7 +32,7 @@ jobs:
           echo "DB_PASSWORD=$DB_PASSWORD" >> .env
           echo "DB_DIALECT=$DB_DIALECT" >> .env
           echo "DB_NAME=$DB_NAME" >> .env
-        
+
       - name: Compress webapp
         run: zip -r webapp.zip .
 
@@ -85,16 +85,48 @@ jobs:
           echo virtualization_type=\"${{ vars.VIRTUALIZATION_TYPE }}\" >> ./packer/variables.pkrvars.hcl
           cat ./packer/variables.pkrvars.hcl
 
-        
       - name: Install Packer
-        run: |  
+        run: |
           pwd
           ls -la
-          packer init ./packer/ami.pkr.hcl 
-        
+          packer init ./packer/ami.pkr.hcl
+
       - name: Build AMI
         env:
           AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_EC2}}
           AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_EC2}}
         run: |
           packer build --var-file=./packer/variables.pkrvars.hcl ./packer/ami.pkr.hcl
+          sudo apt-get install jq
+          ami_id=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d':' -f2)
+          echo "AMI ID: $ami_id"
+          echo "AMI_BUILD_ID=$ami_id" >> $GITHUB_ENV
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
+          aws-secret-access-key: ${{secrets.AWS_DEMO_SECRET_ACCESS_KEY}}
+          aws-region: ${{secrets.AWS_REGION}}
+
+      - name: Update Launch Template and Trigger Instance Refresh
+        run: |
+          # Update Launch Template version with the latest AMI ID
+          aws ec2 create-launch-template-version --launch-template-id ${{ secrets.LAUNCH_TEMPLATE_ID }} --version-description WebVersion2 --source-version 1 --launch-template-data '{"ImageId":"${{ env.AMI_ID }}"}'
+ 
+          # Issue command to auto-scaling group for instance refresh
+          aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ secrets.AUTO_SCALING_GROUP_NAME }}
+ 
+      - name: Wait for Instance Refresh to Complete
+        run: |
+          # Use AWS CLI to check the status of instance refresh
+          status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{ secrets.AUTO_SCALING_GROUP_NAME }} --query 'InstanceRefreshes[0].Status' --output text)
+          while [[ "$status" != "Successful" && "$status" != "Failed" ]]; do
+            sleep 60
+            status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{ secrets.AUTO_SCALING_GROUP_NAME }} --query 'InstanceRefreshes[0].Status' --output text)
+          done
+ 
+          # Exit with an error if instance refresh failed
+          if [ "$status" == "Failed" ]; then
+            exit 1
+          fi
